name: linter-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      ## Получаем последнюю версию репозитория
      - uses: actions/checkout@v2
      ## Устанавливаем Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      ## Выполняем команду install описанную в make файле проекта
      - name: npm install
        run: |
          make install
        env:
          CI: true
      ## запуск линтера
      - name: Run linter
        run: |
          make lint